#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorld.Resource", IsApplication=true)]

namespace HelloWorld
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int MainFragment = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int MySuperTextView = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int btn_add_list = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int btn_edit_drill = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int btn_playsound = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int btn_quiz_next = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int btn_quiz_previous = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int btn_show_answer = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int btn_start_quiz = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int button4 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button5 = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout2 = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int mylistview = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int text_mean = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dictionary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditDrill = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Quiz = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Top = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SuperText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
